### ISSUE TITLE
Unable to obtain key from abc.com

### ISSUE THREAD

**Issue by superlogix** [DevLARLEY/WidevineProxy2#11]
test url: https://abc.com/episode/01523e32-d60a-43ae-acb8-6acb8fec2b4f/playlist/PL551127435
Possible cause: The mpd file contains multiple pssh.

**Comment by DevLARLEY** [comment]
![wvp2](https://github.com/user-attachments/assets/08785a2d-1c49-4659-bd00-372d6a10aee3)
works for me

**Comment by robak29** [comment]
> test url: https://abc.com/episode/01523e32-d60a-43ae-acb8-6acb8fec2b4f/playlist/PL551127435 Possible cause: The mpd file contains multiple pssh.

Out of curiosity, I checked it and it looks like Chrome doesn't show the keys for this material, but Firefox does.

Use Firefox @superlogix

**Comment by Vangelis66** [comment]
> Possible cause: The mpd file contains **multiple pssh**

I downloaded (whitelisted US IP required) and manually parsed the MPD for 

https://abc.com/episode/3e89406e-3ffb-46da-b8b1-3155dc9d6584/playlist/PL551127435

(free, without the need for an ABC account);
I found out they employ three (3) different `PSSH`s there: 

1. audio:

`default_KID="3d651b51-0e53-4bda-88e5-ca0284104af6"`

PSSH:

`AAAAk3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAHMIARIgM2Q2NTFiNTEwZTUzNGJkYTg4ZTVjYTAyODQxMDRhZjYaBHZkbXMiRzQxZWM3NWFkMTQxZTQzNmQ4ZjcwMTE3ZGJmZTIyZjcwX2FldWYxXzM0M2U3NTk4MjE3NzQwZGRhYTg0ZjkyNjc5MTcyOTk5`

2. HD (>=720p60) video

`default_KID="3258a371-9c77-46e2-b6b5-4d949386f529"`

PSSH:

`AAAAk3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAHMIARIgMzI1OGEzNzE5Yzc3NDZlMmI2YjU0ZDk0OTM4NmY1MjkaBHZkbXMiRzQxZWM3NWFkMTQxZTQzNmQ4ZjcwMTE3ZGJmZTIyZjcwX2FldWYxXzM0M2U3NTk4MjE3NzQwZGRhYTg0ZjkyNjc5MTcyOTk5`

3. SD (=<540p30) video

`default_KID="fd4fde2d-e55e-4005-b2a5-33ced83d2d34"`

PSSH:

`AAAAk3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAHMIARIgZmQ0ZmRlMmRlNTVlNDAwNWIyYTUzM2NlZDgzZDJkMzQaBHZkbXMiRzQxZWM3NWFkMTQxZTQzNmQ4ZjcwMTE3ZGJmZTIyZjcwX2FldWYxXzM0M2U3NTk4MjE3NzQwZGRhYTg0ZjkyNjc5MTcyOTk5`

LicURL for ALL three is:

```
https://content-aeuf1.uplynk.com/wv?b=41ec75ad141e436d8f70117dbfe22f70&amp;v=41ec75ad141e436d8f70117dbfe22f70&amp;pbs=343e7598217740ddaa84f92679172999
```
> **Chrome** doesn't show the keys for this material, but **Firefox** does

Can confirm, but using **Supermium** (Cr**126**-based fork) instead of Google Chrome :wink: ; the real question   now is: Why (Chrome-based doesn't work, Firefox-based does) ?

**OT**/**FYI**: `yt-dlp` still seems to be able to access non-**cenc** mobile (HLSe) streams of the same resolutions like the DRM'd desktop MPEG-DASH ones (if you don't want to mess with **widevive** stuff, that is :wink: ): 

<details>
<summary>yt-dlp -F "https://abc.com/episode/3e89406e-3ffb-46da-b8b1-3155dc9d6584/playlist/PL551127435"</summary>

```console
[Go] Extracting URL: https://abc.com/episode/3e89406e-3ffb-46da-b8b1-3155dc9d6584/playlist/PL551127435
[Go] PL551127435: Downloading webpage
[Go] vdka36527486: Downloading JSON metadata
[Go] VDKA36527486: Downloading JSON metadata
[Go] VDKA36527486: Downloading m3u8 information
[info] Available formats for VDKA36527486:
ID                                           EXT           RESOLUTION FPS |   FILESIZE   TBR PROTO | VCODEC      ACODEC    MORE INFO
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
ULNK-aac-English_-_Descriptive_Video_Service mp4           audio only     |             m3u8  | audio only  unknown   [EN] English - Descriptive Video Service
ULNK_MPD                                     unknown_video unknown        |             http  | unknown     unknown
ULNK-209                                     mp4           256x144     15 | ~ 64.45MiB  210k m3u8  | avc1.4d000c mp4a.40.5
ULNK-417                                     mp4           416x234     30 | ~128.42MiB  418k m3u8  | avc1.4d000d mp4a.40.5
ULNK-758                                     mp4           640x360     30 | ~233.20MiB  759k m3u8  | avc1.4d001e mp4a.40.5
ULNK-1714                                    mp4           960x540     30 | ~526.74MiB 1714k m3u8  | avc1.4d001f mp4a.40.5
ULNK-3433                                    mp4           1280x720    60 | ~  1.03GiB 3433k m3u8  | avc1.4d0020 mp4a.40.5
ULNK-5026                                    mp4           1280x720    60 | ~  1.51GiB 5027k m3u8  | avc1.640020 mp4a.40.5
ULNK-6181                                    mp4           1280x720    60 | ~  1.85GiB 6181k m3u8  | avc1.640020 mp4a.40.5
```
</details>
